connector:
    name: Dnd Criteo Connector
    jobs:
        criteo_xml_product_export:
            title: dnd_criteo_connector.jobs.criteo_xml_product_export.title
            type:  export
            steps:
                export:
                    title:     dnd_criteo_connector.jobs.xml_product_export.export.title
                    services:
                        reader:    pim_base_connector.reader.doctrine.product
                        processor: dnd_criteo_connector.processor.product_to_flat_array
                        writer:    dnd_criteo_connector.writer.file.xml_product
                    parameters:
                        batch_size: 10