parameters:
    dnd_criteo_connector.job.job_parameters.constraint_collection_provider.product_xml_export.class: Dnd\Bundle\CriteoConnectorBundle\Job\JobParameters\ConstraintCollectionProvider\CriteoExport

services:
    dnd_criteo_connector.job.job_parameters.constraint_collection_provider.product_xml_export:
        class: %dnd_criteo_connector.job.job_parameters.constraint_collection_provider.product_xml_export.class%
        arguments:
            -
                - 'criteo_export_job'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }