parameters:
    dnd_criteo_connector.job.job_parameters.constraint_collection_provider.criteo_product_xml_export.class: Dnd\Bundle\CriteoConnectorBundle\Job\JobParameters\ConstraintCollectionProvider\CriteoProductExport

services:
    dnd_criteo_connector.job.job_parameters.constraint_collection_provider.criteo_product_xml_export:
        class: '%dnd_criteo_connector.job.job_parameters.constraint_collection_provider.criteo_product_xml_export.class%'
        arguments:
            -
                - '%dnd_criteo_connector.job_name.xml_criteo_product_export%'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

