parameters:
    dnd_criteo_connector.job.job_parameters.default_values_provider.criteo_product_xml_export.class: Dnd\Bundle\CriteoConnectorBundle\Job\JobParameters\DefaultValuesProvider\CriteoProductExport

services:
    dnd_criteo_connector.job.job_parameters.default_values_provider.criteo_product_xml_export:
        class: '%dnd_criteo_connector.job.job_parameters.default_values_provider.criteo_product_xml_export.class%'
        arguments:
          - '@pim_connector.job.job_parameters.default_values_provider.simple_csv_export'
          - '@pim_catalog.repository.channel'
          - '@pim_catalog.repository.locale'
          -
                - '%dnd_criteo_connector.job_name.xml_criteo_product_export%'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }