parameters:
  dnd_criteo_connector.processor.product_to_flat_array.class: Dnd\Bundle\CriteoConnectorBundle\Processor\ProductToFlatArrayProcessor

services:
  dnd_criteo_connector.processor.product_to_flat_array:
    class: %dnd_criteo_connector.processor.product_to_flat_array.class%
    arguments:
      - '@pim_serializer'
      - '@pim_catalog.manager.channel'
      - '@pim_catalog.builder.product'
      - ['pim_catalog_file', 'pim_catalog_image']
      - ['pim_catalog_price_collection']
      - %pim_catalog.localization.decimal_separators%
      - %pim_catalog.localization.date_formats%
      - '@pim_catalog.repository.locale'
      - '@pim_catalog.repository.currency'