services:
    dnd_criteo_connector.provider.form.job_instance:
        class: 'Akeneo\Platform\Bundle\ImportExportBundle\Provider\Form\JobInstanceFormProvider'
        arguments:
            -
                dnd_criteo_connector_xml_product_export: dnd-criteo-product-export
        tags:
            - { name: pim_enrich.provider.form, priority: 100 }
