config:
    paths:
        attributes-list: dndcriteoconnector/js/attributes-list
        available-currencies-list: dndcriteoconnector/js/available-currencies-list
    config:
        pim/fetcher-registry:
            fetchers:
                attributes-list:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: dnd_criteo_connector_attributes_list
                available-currencies-list:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: dnd_criteo_connector_available_currencies_list
