config:
    paths:
        dnd/attributes-list: dndcriteoconnector/js/attributes-list
        dnd/currencies-list: dndcriteoconnector/js/currencies-list

    config:
        pim/fetcher-registry:
            fetchers:
                dnd/attributes-list:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: dnd_criteo_connector_attributes_list
                dnd/currencies-list:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: dnd_criteo_connector_currencies_list