dnd_criteo_connector_attributes_list:
    path: /attributes
    defaults: { _controller: dnd_criteo_connector.rest.attribute_controller:listAttributesAction}
    methods: [GET]

dnd_criteo_connector_currencies_list:
    path: /available-currencies
    defaults: { _controller: dnd_criteo_connector.rest.attribute_controller:listCurrenciesAction}
    methods: [GET]
