parameters:
    dnd_criteo_connector.writer.file.xml_product.class: Dnd\Bundle\CriteoConnectorBundle\Writer\File\XmlProductWriter

services:
    dnd_criteo_connector.writer.file.xml_product:
        class: '%dnd_criteo_connector.writer.file.xml_product.class%'
        arguments:
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.category'
            - '@pim_catalog.repository.channel'
            - '@pim_connector.factory.flat_item_buffer'
            - '@pim_connector.writer.file.flat_item_buffer_flusher'
            - 'product'