extensions:
    xml-criteo-product-export-edit:
        module: pim/form/common/edit-form

    xml-criteo-product-export-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: xml-criteo-product-export-edit
        position: 1000

    xml-criteo-product-export-edit-tabs:
        module: pim/form/common/form-tabs
        parent: xml-criteo-product-export-edit
        targetZone: content
        position: 100

    xml-criteo-product-export-edit-properties:
        module: pim/job/common/edit/properties
        parent: xml-criteo-product-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    xml-criteo-product-export-edit-criteo:
        module: pim/job/common/edit/properties
        parent: xml-criteo-product-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 110
        config:
            tabTitle: dnd_criteo_connector.form.job_instance.tab.criteo.title
            tabCode: pim-job-instance-criteo

    xml-criteo-product-export-edit-content:
        module: pim/job/product/edit/content
        parent: xml-criteo-product-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_content_edit
        targetZone: container
        position: 120
        config:
            tabTitle: pim_enrich.form.job_instance.tab.content.title
            tabCode: pim-job-instance-content

    xml-criteo-product-export-edit-history:
        module: pim/common/tab/history
        parent: xml-criteo-product-export-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 130
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    xml-criteo-product-export-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: xml-criteo-product-export-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    xml-criteo-product-export-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: xml-criteo-product-export-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: false

    xml-criteo-product-export-edit-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: xml-criteo-product-export-edit-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.file_path.help

    xml-criteo-product-export-edit-properties-decimal-separator:
        module: pim/job/common/edit/field/decimal-separator
        parent: xml-criteo-product-export-edit-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.decimalSeparator
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.decimal_separator.title
            tooltip: pim_enrich.form.job_instance.tab.properties.decimal_separator.help

    xml-criteo-product-export-edit-properties-date-format:
        module: pim/job/product/edit/field/date-format
        parent: xml-criteo-product-export-edit-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.dateFormat
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.date_format.title
            tooltip: pim_enrich.form.job_instance.tab.properties.date_format.help

    xml-criteo-product-export-edit-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: xml-criteo-product-export-edit-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.delimiter.help

    xml-criteo-product-export-edit-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: xml-criteo-product-export-edit-properties
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.enclosure.help

    xml-criteo-product-export-edit-properties-with-header:
        module: pim/job/common/edit/field/switch
        parent: xml-criteo-product-export-edit-properties
        position: 170
        targetZone: global-settings
        config:
            fieldCode: configuration.withHeader
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.with_header.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_header.help

    xml-criteo-product-export-edit-properties-with-media:
        module: pim/job/common/edit/field/switch
        parent: xml-criteo-product-export-edit-properties
        position: 180
        targetZone: global-settings
        config:
            fieldCode: configuration.with_media
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.with_media.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_media.help

# Criteo Fields Start -------------------------------------------------------------------------------------
    xml-criteo-product-export-edit-properties-pimMediaUrl:
        module: pim/job/common/edit/field/text
        parent: xml-criteo-product-export-edit-criteo
        position: 130
        targetZone: properties
        config:
            fieldCode: configuration.pimMediaUrl
            readOnly: false
            label: dnd_criteo_connector.form.job_instance.tab.criteo.pimMediaUrl.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.pimMediaUrl.help

    xml-criteo-product-export-edit-properties-currency:
     module: available-currencies-list
     parent: xml-criteo-product-export-edit-criteo
     position: 140
     targetZone: properties
     config:
         fieldCode: configuration.currency
         readOnly: false
         label: dnd_criteo_connector.form.job_instance.tab.criteo.currency.title
         tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.currency.help

    xml-criteo-product-export-edit-properties-id:
        module: attributes-list
        parent: xml-criteo-product-export-edit-criteo
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.id
            readOnly: false
            label: dnd_criteo_connector.form.job_instance.tab.criteo.id.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.id.help

    xml-criteo-product-export-edit-properties-name:
        module: attributes-list
        parent: xml-criteo-product-export-edit-criteo
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.name
            readOnly: false
            label: dnd_criteo_connector.form.job_instance.tab.criteo.name.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.name.help

    xml-criteo-product-export-edit-properties-description:
        module: attributes-list
        parent: xml-criteo-product-export-edit-criteo
        position: 170
        targetZone: global-settings
        config:
            fieldCode: configuration.description
            readOnly: false
            label: dnd_criteo_connector.form.job_instance.tab.criteo.description.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.description.help

    xml-criteo-product-export-edit-properties-productUrl:
        module: attributes-list
        parent: xml-criteo-product-export-edit-criteo
        position: 180
        targetZone: global-settings
        config:
            fieldCode: configuration.productUrl
            readOnly: false
            label: dnd_criteo_connector.form.job_instance.tab.criteo.productUrl.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.productUrl.help

    xml-criteo-product-export-edit-properties-smallImage:
        module: attributes-list
        parent: xml-criteo-product-export-edit-criteo
        position: 190
        targetZone: global-settings
        config:
            fieldCode: configuration.smallImage
            readOnly: false
            label: dnd_criteo_connector.form.job_instance.tab.criteo.smallImage.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.smallImage.help

    xml-criteo-product-export-edit-properties-bigImage:
        module: attributes-list
        parent: xml-criteo-product-export-edit-criteo
        position: 200
        targetZone: global-settings
        config:
            fieldCode: configuration.bigImage
            readOnly: false
            label: dnd_criteo_connector.form.job_instance.tab.criteo.bigImage.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.bigImage.help

    xml-criteo-product-export-edit-properties-price:
        module: attributes-list
        parent: xml-criteo-product-export-edit-criteo
        position: 210
        targetZone: global-settings
        config:
            fieldCode: configuration.price
            readOnly: false
            label: dnd_criteo_connector.form.job_instance.tab.criteo.price.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.price.help

    xml-criteo-product-export-edit-properties-retailPrice:
        module: attributes-list
        parent: xml-criteo-product-export-edit-criteo
        position: 220
        targetZone: global-settings
        config:
            fieldCode: configuration.retailPrice
            readOnly: false
            label: dnd_criteo_connector.form.job_instance.tab.criteo.retailPrice.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.retailPrice.help

    xml-criteo-product-export-edit-properties-recommendable:
        module: attributes-list
        parent: xml-criteo-product-export-edit-criteo
        position: 230
        targetZone: global-settings
        config:
            fieldCode: configuration.recommendable
            readOnly: false
            label: dnd_criteo_connector.form.job_instance.tab.criteo.recommendable.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.recommendable.help

    xml-criteo-product-export-edit-properties-includeCategories:
        module: pim/job/common/edit/field/switch
        parent: xml-criteo-product-export-edit-criteo
        position: 240
        targetZone: global-settings
        config:
            fieldCode: configuration.includeCategories
            readOnly: false
            label: dnd_criteo_connector.form.job_instance.tab.criteo.includeCategories.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.includeCategories.help

    # Criteo Fields End ---------------------------------------------------------------------------------------

    xml-criteo-product-export-edit-content-structure:
        module: pim/job/product/edit/content/structure
        parent: xml-criteo-product-export-edit-content
        targetZone: structure-filters
        position: 100

    xml-criteo-product-export-edit-label:
        module: pim/job/common/edit/label
        parent: xml-criteo-product-export-edit
        targetZone: title
        position: 100

    xml-criteo-product-export-edit-meta:
        module: pim/job/common/edit/meta
        parent: xml-criteo-product-export-edit
        targetZone: meta
        position: 100

    xml-criteo-product-export-edit-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: xml-criteo-product-export-edit
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    xml-criteo-product-export-edit-delete:
        module: pim/job/export/edit/delete
        parent: xml-criteo-product-export-edit
        targetZone: buttons
        aclResourceId: pim_importexport_export_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.job_instance
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    xml-criteo-product-export-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: xml-criteo-product-export-edit
        targetZone: buttons
        position: 120

    xml-criteo-product-export-edit-save:
        module: pim/job-instance-export-edit-form/save
        parent: xml-criteo-product-export-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_export_profile_show

    xml-criteo-product-export-edit-state:
        module: pim/form/common/state
        parent: xml-criteo-product-export-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title


    xml-criteo-product-export-edit-content-structure-scope:
        module: pim/job/product/edit/content/structure/scope
        parent: xml-criteo-product-export-edit-content-structure
        targetZone: filters
        position: 90

    xml-criteo-product-export-edit-content-structure-locales:
        module: pim/job/product/edit/content/structure/locales
        parent: xml-criteo-product-export-edit-content-structure
        targetZone: filters
        position: 100

    xml-criteo-product-export-edit-content-structure-attributes:
        module: pim/job/product/edit/content/structure/attributes
        parent: xml-criteo-product-export-edit-content-structure
        targetZone: filters
        position: 110

    xml-criteo-product-export-edit-content-data:
        module: pim/job/product/edit/content/data
        parent: xml-criteo-product-export-edit-content
        targetZone: data-filters
        config:
            filters:
                -
                    field: family
                    view: akeneo-product-family-filter
                -
                    field: enabled
                    view: akeneo-product-enabled-filter
                -
                    field: completeness
                    view: akeneo-product-completeness-filter
                -
                    field: updated
                    view: akeneo-product-updated-filter
                -
                    field: categories
                    view: akeneo-product-category-filter

    xml-criteo-product-export-edit-content-default-attribute-filters:
        module: pim/job/product/edit/content/data/default-attribute-filters
        parent: xml-criteo-product-export-edit-content-data
        config:
            types: [pim_catalog_identifier]

    xml-criteo-product-export-edit-content-data-help:
        module: pim/job/product/edit/content/data/help
        parent: xml-criteo-product-export-edit-content-data

    xml-criteo-product-export-edit-validation:
        module: pim/job/common/edit/validation
        parent: xml-criteo-product-export-edit

    xml-criteo-product-export-edit-content-data-add-filter:
        module: pim/job/product/edit/content/data/add-select/attribute
        parent: xml-criteo-product-export-edit-content-data
        targetZone: headings
        position: 90
