extensions:
    xml-criteo-product-export-show:
        module: pim/form/common/edit-form

    xml-criteo-product-export-show-tabs:
        module: pim/form/common/form-tabs
        parent: xml-criteo-product-export-show
        targetZone: content
        position: 100

    xml-criteo-product-export-show-properties:
        module: pim/job/common/edit/properties
        parent: xml-criteo-product-export-show-tabs
        aclResourceId: pim_importexport_export_profile_property_show
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    xml-criteo-product-export-show-criteo:
        module: pim/job/common/edit/properties
        parent: xml-criteo-product-export-show-tabs
        aclResourceId: pim_importexport_export_profile_property_show
        targetZone: container
        position: 110
        config:
            tabTitle: dnd_criteo_connector.form.job_instance.tab.criteo.title
            tabCode: pim-job-instance-criteo

    xml-criteo-product-export-show-content:
        module: pim/job/product/edit/content
        parent: xml-criteo-product-export-show-tabs
        aclResourceId: pim_importexport_export_profile_content_show
        targetZone: container
        position: 120
        config:
            tabTitle: pim_enrich.form.job_instance.tab.content.title
            tabCode: pim-job-instance-content

    xml-criteo-product-export-show-history:
        module: pim/common/tab/history
        parent: xml-criteo-product-export-show-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 130
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    xml-criteo-product-export-show-properties-code:
        module: pim/job/common/edit/field/text
        parent: xml-criteo-product-export-show-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    xml-criteo-product-export-show-properties-label:
        module: pim/job/common/edit/field/text
        parent: xml-criteo-product-export-show-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: true

    xml-criteo-product-export-show-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: xml-criteo-product-export-show-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.file_path.help

    xml-criteo-product-export-show-properties-decimal-separator:
        module: pim/job/common/edit/field/decimal-separator
        parent: xml-criteo-product-export-show-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.decimalSeparator
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.decimal_separator.title
            tooltip: pim_enrich.form.job_instance.tab.properties.decimal_separator.help

    xml-criteo-product-export-show-properties-date-format:
        module: pim/job/product/edit/field/date-format
        parent: xml-criteo-product-export-show-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.dateFormat
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.date_format.title
            tooltip: pim_enrich.form.job_instance.tab.properties.date_format.help

    xml-criteo-product-export-show-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: xml-criteo-product-export-show-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.delimiter.help

    xml-criteo-product-export-show-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: xml-criteo-product-export-show-properties
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.enclosure.help

    xml-criteo-product-export-show-properties-with-header:
        module: pim/job/common/edit/field/switch
        parent: xml-criteo-product-export-show-properties
        position: 170
        targetZone: global-settings
        config:
            fieldCode: configuration.withHeader
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.with_header.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_header.help

    xml-criteo-product-export-show-properties-with-media:
        module: pim/job/common/edit/field/switch
        parent: xml-criteo-product-export-show-properties
        position: 180
        targetZone: global-settings
        config:
            fieldCode: configuration.with_media
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.with_media.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_media.help

# Criteo Fields Start -------------------------------------------------------------------------------------
    xml-criteo-product-export-show-properties-pimMediaUrl:
        module: pim/job/common/edit/field/text
        parent: xml-criteo-product-export-show-criteo
        position: 130
        targetZone: properties
        config:
            fieldCode: configuration.pimMediaUrl
            readOnly: true
            label: dnd_criteo_connector.form.job_instance.tab.criteo.pimMediaUrl.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.pimMediaUrl.help

    xml-criteo-product-export-show-properties-currency:
     module: available-currencies-list
     parent: xml-criteo-product-export-show-criteo
     position: 140
     targetZone: properties
     config:
         fieldCode: configuration.currency
         readOnly: true
         label: dnd_criteo_connector.form.job_instance.tab.criteo.currency.title
         tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.currency.help

    xml-criteo-product-export-show-properties-id:
        module: attributes-list
        parent: xml-criteo-product-export-show-criteo
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.id
            readOnly: true
            label: dnd_criteo_connector.form.job_instance.tab.criteo.id.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.id.help

    xml-criteo-product-export-show-properties-name:
        module: attributes-list
        parent: xml-criteo-product-export-show-criteo
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.name
            readOnly: true
            label: dnd_criteo_connector.form.job_instance.tab.criteo.name.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.name.help

    xml-criteo-product-export-show-properties-description:
        module: attributes-list
        parent: xml-criteo-product-export-show-criteo
        position: 170
        targetZone: global-settings
        config:
            fieldCode: configuration.description
            readOnly: true
            label: dnd_criteo_connector.form.job_instance.tab.criteo.description.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.description.help

    xml-criteo-product-export-show-properties-productUrl:
        module: attributes-list
        parent: xml-criteo-product-export-show-criteo
        position: 180
        targetZone: global-settings
        config:
            fieldCode: configuration.productUrl
            readOnly: true
            label: dnd_criteo_connector.form.job_instance.tab.criteo.productUrl.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.productUrl.help

    xml-criteo-product-export-show-properties-smallImage:
        module: attributes-list
        parent: xml-criteo-product-export-show-criteo
        position: 190
        targetZone: global-settings
        config:
            fieldCode: configuration.smallImage
            readOnly: true
            label: dnd_criteo_connector.form.job_instance.tab.criteo.smallImage.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.smallImage.help

    xml-criteo-product-export-show-properties-bigImage:
        module: attributes-list
        parent: xml-criteo-product-export-show-criteo
        position: 200
        targetZone: global-settings
        config:
            fieldCode: configuration.bigImage
            readOnly: true
            label: dnd_criteo_connector.form.job_instance.tab.criteo.bigImage.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.bigImage.help

    xml-criteo-product-export-show-properties-price:
        module: attributes-list
        parent: xml-criteo-product-export-show-criteo
        position: 210
        targetZone: global-settings
        config:
            fieldCode: configuration.price
            readOnly: true
            label: dnd_criteo_connector.form.job_instance.tab.criteo.price.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.price.help

    xml-criteo-product-export-show-properties-retailPrice:
        module: attributes-list
        parent: xml-criteo-product-export-show-criteo
        position: 220
        targetZone: global-settings
        config:
            fieldCode: configuration.retailPrice
            readOnly: true
            label: dnd_criteo_connector.form.job_instance.tab.criteo.retailPrice.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.retailPrice.help

    xml-criteo-product-export-show-properties-recommendable:
        module: attributes-list
        parent: xml-criteo-product-export-show-criteo
        position: 230
        targetZone: global-settings
        config:
            fieldCode: configuration.recommendable
            readOnly: true
            label: dnd_criteo_connector.form.job_instance.tab.criteo.recommendable.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.recommendable.help

    xml-criteo-product-export-show-properties-includeCategories:
        module: pim/job/common/edit/field/switch
        parent: xml-criteo-product-export-show-criteo
        position: 240
        targetZone: global-settings
        config:
            fieldCode: configuration.includeCategories
            readOnly: true
            label: dnd_criteo_connector.form.job_instance.tab.criteo.includeCategories.title
            tooltip: dnd_criteo_connector.form.job_instance.tab.criteo.includeCategories.help

    # Criteo Fields End ---------------------------------------------------------------------------------------

    xml-criteo-product-export-show-content-structure:
        module: pim/job/product/edit/content/structure
        parent: xml-criteo-product-export-show-content
        targetZone: structure-filters
        position: 100

    xml-criteo-product-export-show-label:
        module: pim/job/common/edit/label
        parent: xml-criteo-product-export-show
        targetZone: title
        position: 100

    xml-criteo-product-export-show-meta:
        module: pim/job/common/edit/meta
        parent: xml-criteo-product-export-show
        targetZone: meta
        position: 100

    xml-criteo-product-export-show-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: xml-criteo-product-export-show
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    xml-criteo-product-export-show-content-structure-scope:
        module: pim/job/product/edit/content/structure/scope
        parent: xml-criteo-product-export-show-content-structure
        targetZone: filters
        position: 90
        config:
            readOnly: true

    xml-criteo-product-export-show-content-structure-locales:
        module: pim/job/product/edit/content/structure/locales
        parent: xml-criteo-product-export-show-content-structure
        targetZone: filters
        position: 100
        config:
            readOnly: true

    xml-criteo-product-export-show-content-structure-attributes:
        module: pim/job/product/edit/content/structure/attributes
        parent: xml-criteo-product-export-show-content-structure
        targetZone: filters
        position: 110
        config:
            readOnly: true

    xml-criteo-product-export-show-content-data:
        module: pim/job/product/edit/content/data
        parent: xml-criteo-product-export-show-content
        targetZone: data-filters
        config:
            filters:
                -
                    field: family
                    view: akeneo-product-family-filter
                -
                    field: enabled
                    view: akeneo-product-enabled-filter
                -
                    field: completeness
                    view: akeneo-product-completeness-filter
                -
                    field: updated
                    view: akeneo-product-updated-filter
                -
                    field: categories
                    view: akeneo-product-category-filter

    xml-criteo-product-export-show-content-readonly:
        module: pim/job/product/edit/content/readonly
        parent: xml-criteo-product-export-show-content

    xml-criteo-product-export-show-content-default-attribute-filters:
        module: pim/job/product/edit/content/data/default-attribute-filters
        parent: xml-criteo-product-export-show-content-data
        config:
            types: [pim_catalog_identifier]

    xml-criteo-product-export-show-content-data-help:
        module: pim/job/product/edit/content/data/help
        parent: xml-criteo-product-export-show-content-data

    xml-criteo-product-export-show-edit:
        module: pim/common/redirect
        parent: xml-criteo-product-export-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_export_profile_edit
            identifier:
                path: code
                name: code

    xml-criteo-product-export-show-launch:
        module: pim/job/common/edit/launch
        parent: xml-criteo-product-export-show
        targetZone: buttons
        position: 110
        config:
            label: pim_enrich.form.job_instance.button.export.title
            route: pim_enrich_job_instance_rest_export_launch
            identifier:
                path: code
                name: code
